### ISSUE TITLE
Upstream is outdated and broken

### ISSUE THREAD

**Issue by alexanderkjeldaas** [MiKTeX/docker-miktex#15]
Trying this system for the first time, I get the following error:

```
[Loading MPS to PDF converter (version 2006.09.02).]
)

! LaTeX Error: File `epstopdf-base.sty' not found.
```

The upstream image is 7 (or 9?) months old and building from scratch fixes this issue.

**Comment by tburba** [comment]
I'm using this system since summer, and recent refactoring of the "oberdiek" package bit me as well.

I'm not using the plain upstream image as my task needs some more software. At the moment building from scratch would provide more challenges than benefits.

In my Dockerfile that does `FROM miktex/miktex`, I was able to add a workaround:

`RUN mpm --admin --verbose --update --install=...`

Looks like the key point is `--update`. Now every `docker run` automatically installs kvoptions, infwarerr, pdftexcmds, pdfescape, letltxmacro, bitset, atbegshi, atveryend, rerunfilecheck, epstopdf-pkg :)

I have multiple occurrences of --install for optimization, as my task needs approx. 50 more packages than provided in the basic distribution, and auto-installing them takes a significant amount of time. **The problem that still remains:** until December it was possible to pre-install every missing package via --install, but these new ones are different. For example, --install=kvoptions fails with:

> 2019-12-18 10:37:55,401Z INFO  mpmcli - Operating on the shared (system-wide) MiKTeX setup
> 2019-12-18 10:37:55,707Z FATAL mpmcli - The requested package is unknown.
> 2019-12-18 10:37:55,707Z FATAL mpmcli - Info: name="kvoptions"
> 2019-12-18 10:37:55,707Z FATAL mpmcli - Source: Libraries/MiKTeX/PackageManager/PackageDataStore.cpp
> 2019-12-18 10:37:55,707Z FATAL mpmcli - Line: 397

What more can be done via mpm to avoid auto-installation?

**Comment by cmorty** [comment]
Alsways running `mpm --admin --verbose --update `  could fix this issue. Yet building docker images more regularly would be even better.....
