### ISSUE TITLE
Discussion: GitHub Actions for image build

### ISSUE THREAD

**Issue by irishismyname** [MiKTeX/docker-miktex#40]
I'm in a situation where I could really use a working `miktex/miktex:latest` image, but the one currently available (digest ebd838f3) is far enough out of date that it may no longer be usable.

I'd like to at least create a PR for you all (@edocevoli, @PHPirates, @cr0wg4n) to consider if that's in line with the direction this project is going. If not we can just close this issue and I'll figure something else out.

Also commented on #37.

**Comment by PHPirates** [comment]
I believe scheduled github actions will be disabled after 60 days of repo inactivity, so that doesn't really help (unless you hack yourself around that). I guess best you can do is fork and push your own image with regular updates, like [I did](https://github.com/Hannah-Sten/TeXiFy-IDEA/pkgs/container/TeXiFy-IDEA%2Fmiktex) and other people are doing as well: https://hub.docker.com/search?q=miktex&sort=updated_at&order=desc

**Comment by irishismyname** [comment]
How often does the image build need to occur to keep it (miktex/miktex:latest) functional?

What do you think about moving this code into the main miktex repo? It looks like that has a sufficient level of activity.

**Comment by PHPirates** [comment]
Ideally it would be integrated in whatever process is used to release new MiKTeX versions, but that only @edocevoli can answer whether he is up for doing that.

**Comment by cr0wg4n** [comment]
Hello @irishismyname, as mentioned by @PHPirates, I have forked the repository and I periodically utilize this GitHub action: https://github.com/cr0wg4n/docker-miktex/blob/master/.github/workflows/build-and-push.yml. However, I am not currently using the image, but this method worked very well.
