### ISSUE TITLE
How to pre-install more packages for CI/CD?

### ISSUE THREAD

**Issue by 1kastner** [MiKTeX/docker-miktex#9]
I'd like to have more pre-installed packages, not the lightweight solution.
I started with texlive-full but locally as we use miktex I realized that there are small version differences so what locally works does not work on the server.
Therefore, I wanted to harmonize the setting.
Is there a commandline argument I could use for installing more tex packages?
Like 
```
If you have just installed MiKTeX, then you have the option to upgrade your
installation to a standard TeX system. Just click the Upgrade button. 
Please be aware that this starts a ~200MB download.
```
but just from the commandline.
For CI/CD later the already-prepared docker image would be pulled (from an internal repo) and then the runtime should be rather low and the need of network communication as well.

**Comment by 1kastner** [comment]
See the Dockerfile in #8.

**Comment by RobertHeim** [comment]
Unfortunately the docker file is not available anymore. Do you still got a working example for a CI build?
We have the problem that the image is not installing packages on the fly and neither are we able to use`mpm --install=packagelist` because for almost all packages it says `FATAL mpmcli - The requested package is unknown.`

**Comment by 1kastner** [comment]
I am sorry but I don't have it anymore.
